main:	
	g++ -c -std=c++11 main.cpp entity.cpp Composite.cpp DeadState.cpp InjuredState.cpp NormalState.cpp                  
	g++ -o main main.o entity.o Composite.o DeadState.o InjuredState.o NormalState.o
	./main
	rm *.o main